// Generated by `moi init --experimental-collab`; do not edit this file.
declare module 'moi/collab' {
  import type { ReactElement, ReactNode } from 'react'

  export type CollabJsonValue =
    | null
    | boolean
    | number
    | string
    | CollabJsonValue[]
    | { [key: string]: CollabJsonValue }

  export type CollabIdentity = { id: string; name: string; avatar?: string; color: string }
  export type CollabLocation = { page: string; title?: string }
  export type CollabPresenceRegistration = {
    registrationId: string
    surface: string
    channel: string
    value: CollabJsonValue
  }
  export type CollabParticipant = {
    connectionId: string
    identity: CollabIdentity
    location: CollabLocation | null
    presence: CollabPresenceRegistration[]
  }
  export type CollabOperation =
    | { type: 'set'; key: string; value: CollabJsonValue }
    | { type: 'delete'; key: string }
  export type MutationOutcome =
    | { status: 'committed'; revision: number }
    | { status: 'rejected' | 'unknown'; message: string }

  export type OthersOptions = { scope?: 'page' | 'workspace' }
  export function useSelf(): CollabParticipant | null
  export function useOthers(options?: OthersOptions): CollabParticipant[]
  export type PresenceValue<T> = { participant: CollabParticipant; value: T }
  export function usePresence<T extends CollabJsonValue>(
    channel: string,
    initialValue: T
  ): { value: T; setValue: (value: T) => void; others: PresenceValue<T>[] }

  export type SharedOptions = { scope?: string }
  export type SharedStateOptions<T> = SharedOptions & { defaultValue?: T }
  export type SharedStatus = {
    loaded: boolean
    canWrite: boolean
    isSaving: boolean
    error: string | null
  }
  export function useSharedState<T extends CollabJsonValue>(
    key: string,
    options?: SharedStateOptions<T>
  ): SharedStatus & {
    value: T | undefined
    exists: boolean
    setValue: (value: T) => Promise<MutationOutcome>
    deleteValue: () => Promise<MutationOutcome>
  }
  export function useSharedStore(
    prefix?: string,
    options?: SharedOptions
  ): SharedStatus & {
    entries: Readonly<Record<string, CollabJsonValue>>
    set: (key: string, value: CollabJsonValue) => Promise<MutationOutcome>
    delete: (key: string) => Promise<MutationOutcome>
    batch: (operations: CollabOperation[]) => Promise<MutationOutcome>
  }

  export type ActivityProps = { scope?: 'page' | 'workspace'; className?: string }
  export function Activity(props: ActivityProps): ReactElement
  export type CursorsProps = { surface?: string; children: ReactNode; className?: string }
  export function Cursors(props: CursorsProps): ReactElement
  export type PresenceFieldProps = { target: string; children: ReactNode; className?: string }
  export function PresenceField(props: PresenceFieldProps): ReactElement
  export type SelectionProps = {
    target: string
    selected: boolean
    children: ReactNode
    className?: string
  }
  export function Selection(props: SelectionProps): ReactElement

  // People components. Store ids in shared data, not profiles: a person is
  // always given by id (`id`, or `ids` for several) and resolves to the current
  // name, face, and status through the workspace, including people who have left.
  export type PersonStatus = 'active' | 'away' | 'offline'
  export function usePerson(id: string): {
    id: string
    identity: CollabIdentity | null
    status: PersonStatus
  }
  export type PersonSize = 'xs' | 'sm' | 'md' | 'lg'
  export type PersonProps = {
    id: string
    size?: PersonSize
    avatarOnly?: boolean
    you?: boolean
    detail?: ReactNode
    // The green dot: this person has the workspace open in a visible tab now.
    showStatus?: boolean
    label?: string
    className?: string
  }
  export function Person(props: PersonProps): ReactElement
  export type FacepileProps = {
    ids: string[]
    max?: number
    size?: 'xs' | 'sm' | 'md'
    showStatus?: boolean
    className?: string
  }
  export function Facepile(props: FacepileProps): ReactElement
  export type CursorProps = {
    id: string
    x?: number
    y?: number
    label?: boolean
    className?: string
  }
  export function Cursor(props: CursorProps): ReactElement
  // Wraps anything: the frame hugs a single child element and takes its radius.
  export type PresenceFrameProps = {
    ids: string[]
    icon?: ReactNode
    children: ReactNode
    className?: string
  }
  export function PresenceFrame(props: PresenceFrameProps): ReactElement
  export type GutterPerson = { id: string; target: string }
  export type PresenceGutterProps = {
    people: GutterPerson[]
    children: ReactNode
    className?: string
  }
  export function PresenceGutter(props: PresenceGutterProps): ReactElement
}
