// Generated by `moi init --experimental-collab`; do not edit this file.
declare module 'moi/collab' {
  import type { ReactElement, ReactNode } from 'react'

  export type CollabJsonValue =
    | null
    | boolean
    | number
    | string
    | CollabJsonValue[]
    | { [key: string]: CollabJsonValue }

  export type CollabIdentity = {
    id: string
    name: string
    color: string
    avatar?: string
    email?: string
  }
  export type UserStatus = 'active' | 'away' | 'offline'
  export type CollabUser = CollabIdentity & { status: UserStatus }
  export type PeersOptions = { scope?: 'page' | 'workspace'; status?: 'active' | 'away' }

  // Peers are connected users, deduplicated across tabs, excluding your own user.
  export function useMe(): CollabUser | null
  export function useUser(id: string): CollabUser | null
  export function usePeers(options?: PeersOptions): CollabUser[]

  export type PresenceValue<T> = { connectionId: string; userId: string; value: T }
  // Reading never registers or publishes presence. Values belong to connections.
  export function usePresence<T extends CollabJsonValue>(channel: string): PresenceValue<T>[]
  // Publishes the current value reactively, releasing it on hide or unmount.
  export function usePublishPresence<T extends CollabJsonValue>(channel: string, value: T): void

  export type ActivityProps = { scope?: 'page' | 'workspace'; className?: string }
  export function Activity(props: ActivityProps): ReactElement
  export type CursorsProps = { surface?: string; children: ReactNode; className?: string }
  export function Cursors(props: CursorsProps): ReactElement

  // Targets identify controls across browsers, reordered lists, and record modals.
  // Both components handle focus presence internally.
  export type PresenceFrameProps = { target: string; children: ReactNode; className?: string }
  export function PresenceFrame(props: PresenceFrameProps): ReactElement
  export type PresenceGutterProps = { target: string; children: ReactNode; className?: string }
  export function PresenceGutter(props: PresenceGutterProps): ReactElement
  export type PresenceGroupProps = { children: ReactNode }
  export function PresenceGroup(props: PresenceGroupProps): ReactElement
  export type SelectionProps = {
    target: string
    selected: boolean
    children: ReactNode
    className?: string
  }
  export function Selection(props: SelectionProps): ReactElement

  export type UserSize = 'xs' | 'sm' | 'md' | 'lg'
  export type UserProps = {
    id: string
    size?: UserSize
    avatarOnly?: boolean
    you?: boolean
    detail?: ReactNode
    showStatus?: boolean
    label?: string
    className?: string
  }
  export function User(props: UserProps): ReactElement
  export type FacepileProps = {
    ids: readonly string[]
    max?: number
    size?: 'xs' | 'sm' | 'md'
    showStatus?: boolean
    className?: string
  }
  export function Facepile(props: FacepileProps): ReactElement
}
