// Long-lived `codex app-server` client, one process per workspace.
//
// The app-server is a JSON-RPC 2.0 server over stdio (newline-delimited JSON)
// bundled with the Codex CLI — the same protocol the official VS Code
// extension drives. One process serves every thread of one workspace: threads
// carry their own cwd, but env is process-level, so per-workspace env
// injection (moi's `workspaceEnv`) forces one process per workspace — same
// frozen-at-spawn semantics as the Claude Code subprocess (`cc-session.ts`).
//
// Protocol shapes here are hand-written against the bindings generated by
// `codex app-server generate-ts` at CLI 0.144.5, and read defensively — see
// docs/harnesses/codex.md.
import type { Model, SessionInfo, StreamEvent } from '@/lib/types'

import {
  type CodexModel,
  type CodexThread,
  codexModelToModel,
  codexThreadToEvents,
  codexThreadToSessionInfo
} from './codex-adapter'
import { debug } from './debug'
import { resolveWorkspaceEnv } from './workspace-env'

const REQUEST_TIMEOUT_MS = 30_000

type Json = Record<string, unknown>
type NotificationListener = (method: string, params: Json) => void

export type CodexClient = {
  rpc: <T>(method: string, params?: Json) => Promise<T>
  onNotification: (l: NotificationListener) => () => void
  isAlive: () => boolean
  workspacePath: string
}

// Locate the codex binary. Codex Desktop does NOT guarantee a `codex` on PATH
// (it manages an app-internal install), so honor an explicit override first.
export function findCodexBinary(): string | null {
  const explicit = process.env.CODEX_CLI_PATH
  if (explicit) return explicit
  return Bun.which('codex')
}

type ClientRecord = {
  client: CodexClient
  proc: ReturnType<typeof Bun.spawn>
}

const clients = new Map<string, Promise<ClientRecord>>() // key: workspacePath

async function startClient(workspacePath: string): Promise<ClientRecord> {
  const bin = findCodexBinary()
  if (!bin) {
    throw new Error(
      'codex CLI not found — install it (`npm i -g @openai/codex`) or set CODEX_CLI_PATH'
    )
  }

  const workspaceEnv = await resolveWorkspaceEnv(workspacePath)
  const proc = Bun.spawn([bin, 'app-server'], {
    cwd: workspacePath,
    stdin: 'pipe',
    stdout: 'pipe',
    stderr: 'pipe',
    env: { ...process.env, ...workspaceEnv }
  })

  let alive = true
  let nextId = 1
  const pending = new Map<
    number,
    { resolve: (v: unknown) => void; reject: (e: Error) => void; timer: Timer }
  >()
  const listeners = new Set<NotificationListener>()

  function send(obj: Json) {
    proc.stdin.write(JSON.stringify(obj) + '\n')
    proc.stdin.flush()
  }

  function rpc<T>(method: string, params: Json = {}): Promise<T> {
    if (!alive) return Promise.reject(new Error('codex app-server not running'))
    const id = nextId++
    send({ jsonrpc: '2.0', id, method, params })
    return new Promise<T>((resolve, reject) => {
      const timer = setTimeout(() => {
        pending.delete(id)
        reject(new Error(`codex rpc timeout: ${method}`))
      }, REQUEST_TIMEOUT_MS)
      pending.set(id, { resolve: resolve as (v: unknown) => void, reject, timer })
    })
  }

  function fanout(method: string, params: Json) {
    for (const l of listeners) {
      try {
        l(method, params)
      } catch (err) {
        console.error('[codex] notification listener threw', err)
      }
    }
  }

  // Server→client requests MUST be answered or the turn hangs. We run threads
  // with `approvalPolicy: 'never'`, so approval requests should not occur —
  // accept defensively if one does; reject anything else as unsupported.
  function answerServerRequest(msg: Json) {
    const method = msg.method as string
    if (method.endsWith('requestApproval') || method === 'applyPatchApproval') {
      send({ jsonrpc: '2.0', id: msg.id, result: { decision: 'accept' } })
    } else if (method === 'execCommandApproval') {
      send({ jsonrpc: '2.0', id: msg.id, result: { decision: 'approved' } })
    } else {
      send({
        jsonrpc: '2.0',
        id: msg.id,
        error: { code: -32601, message: `moi does not handle ${method}` }
      })
    }
  }

  function handleLine(line: string) {
    if (!line.trim()) return
    let msg: Json
    try {
      msg = JSON.parse(line) as Json
    } catch {
      return
    }
    if ('id' in msg && 'method' in msg) {
      answerServerRequest(msg)
    } else if ('id' in msg) {
      const p = pending.get(msg.id as number)
      if (!p) return
      pending.delete(msg.id as number)
      clearTimeout(p.timer)
      if ('error' in msg) {
        const e = msg.error as { message?: string } | undefined
        p.reject(new Error(e?.message ?? JSON.stringify(msg.error)))
      } else {
        p.resolve(msg.result)
      }
    } else if (typeof msg.method === 'string') {
      fanout(msg.method, (msg.params ?? {}) as Json)
    }
  }

  async function readLoop() {
    const reader = (proc.stdout as ReadableStream<Uint8Array>).getReader()
    const decoder = new TextDecoder()
    let buf = ''
    try {
      while (true) {
        const { done, value } = await reader.read()
        if (done) break
        buf += decoder.decode(value, { stream: true })
        let nl: number
        while ((nl = buf.indexOf('\n')) >= 0) {
          handleLine(buf.slice(0, nl))
          buf = buf.slice(nl + 1)
        }
      }
    } finally {
      alive = false
      if (clients.get(workspacePath) === recordPromise) clients.delete(workspacePath)
      for (const [, p] of pending) {
        clearTimeout(p.timer)
        p.reject(new Error('codex app-server exited'))
      }
      pending.clear()
      fanout('__exit', {})
      debug(`codex app-server exited ws=${workspacePath}`)
    }
  }

  async function drainStderr() {
    const reader = (proc.stderr as ReadableStream<Uint8Array>).getReader()
    const decoder = new TextDecoder()
    while (true) {
      const { done, value } = await reader.read()
      if (done) break
      const text = decoder.decode(value).trim()
      if (text) console.error('[codex stderr]', text)
    }
  }

  // recordPromise is referenced by readLoop's cleanup to make sure we only
  // delete our own registry entry (not a replacement spawned after a crash).
  const client: CodexClient = {
    rpc,
    onNotification(l) {
      listeners.add(l)
      return () => listeners.delete(l)
    },
    isAlive: () => alive,
    workspacePath
  }
  const record: ClientRecord = { client, proc }
  const recordPromise = Promise.resolve(record)

  void readLoop()
  void drainStderr()

  await rpc('initialize', {
    clientInfo: { name: 'moi', title: 'moi', version: '0.1' },
    capabilities: { experimentalApi: false, requestAttestation: false }
  })
  send({ jsonrpc: '2.0', method: 'initialized', params: {} })
  debug(`codex app-server started ws=${workspacePath} bin=${bin}`)
  return record
}

export async function getCodexClient(workspacePath: string): Promise<CodexClient> {
  const existing = clients.get(workspacePath)
  if (existing) {
    const rec = await existing
    if (rec.client.isAlive()) return rec.client
    clients.delete(workspacePath)
  }
  const started = startClient(workspacePath)
  clients.set(workspacePath, started)
  try {
    return (await started).client
  } catch (err) {
    clients.delete(workspacePath)
    throw err
  }
}

// Kill a workspace's app-server so the next message respawns it with fresh
// env (env is process-level and frozen at spawn). Mirrors the semantics of
// cc-session's restartWorkspaceSessions; in-flight turns are lost.
export function killCodexWorkspace(workspacePath: string): void {
  const rec = clients.get(workspacePath)
  if (!rec) return
  clients.delete(workspacePath)
  void rec.then(r => r.proc.kill()).catch(() => {})
}

// Server shutdown: kill every app-server so no codex process is orphaned.
export function killAllCodexClients(): void {
  for (const [path, rec] of clients) {
    clients.delete(path)
    void rec.then(r => r.proc.kill()).catch(() => {})
  }
}

// ---- discovery (sessions list / models / cold history) -----------------------

// Threads whose recorded cwd is exactly the workspace path, newest first.
export async function getCodexSessions(workspacePath: string): Promise<SessionInfo[]> {
  try {
    const client = await getCodexClient(workspacePath)
    const res = await client.rpc<{ data?: CodexThread[] }>('thread/list', {
      cwd: workspacePath,
      limit: 50
    })
    return (res.data ?? []).map(codexThreadToSessionInfo)
  } catch (err) {
    console.error('[codex] thread/list failed', err)
    return []
  }
}

// Account-wide model catalog (identical for every workspace); cached like the
// Claude list in agent.ts, cleared on failure so a later call can retry.
let codexModelsPromise: Promise<Model[]> | null = null

export function getCodexModels(workspacePath: string): Promise<Model[]> {
  if (!codexModelsPromise) {
    codexModelsPromise = (async () => {
      const client = await getCodexClient(workspacePath)
      const res = await client.rpc<{ data?: CodexModel[] }>('model/list', {})
      return (res.data ?? []).filter(m => !m.hidden).map(codexModelToModel)
    })().catch(err => {
      codexModelsPromise = null
      throw err
    })
  }
  return codexModelsPromise
}

// Static history replay for the REST events endpoint (no live subscription).
export async function getCodexThreadEvents(
  workspacePath: string,
  threadId: string
): Promise<StreamEvent[]> {
  try {
    const client = await getCodexClient(workspacePath)
    const res = await client.rpc<{ thread?: CodexThread }>('thread/read', {
      threadId,
      includeTurns: true
    })
    return res.thread ? codexThreadToEvents(res.thread) : []
  } catch {
    return []
  }
}
