// Scaffolding for a workspace's `.moi/` root, laid down by `moi init` (and
// `moi openclaw init`). Creates `.moi/widgets/`, writes the widget
// dependency manifest, and installs dependencies — so the agent never has to
// bootstrap the folder itself.
import { mkdir } from 'node:fs/promises'
import { join } from 'node:path'

// Dependency set available to widgets. `react`/`react-dom` are stubs — at
// runtime they resolve from esm.sh via the browser importmap; they're listed
// so editors pick up the correct types.
export const MOI_PACKAGE_JSON = {
  name: 'widgets',
  private: true,
  dependencies: {
    '@tabler/icons-react': '^3.40.0',
    tailwindcss: '^4.0.0',
    react: '^19.0.0',
    'react-dom': '^19.0.0'
  },
  devDependencies: {
    '@types/react': '^19.0.0',
    '@types/react-dom': '^19.0.0'
  }
} as const

// Ambient types for applets (widgets & views). Editor DX only — the moi
// bundler resolves the `moi` module and asset imports at build time without any
// declarations. Lives at `.moi/` root, NOT inside widgets/views, so it isn't
// picked up by the `.ts` build glob and compiled as an applet.
export const APPLET_ENV_DTS = `// Auto-generated by \`moi init\`. Ambient types for widgets & views.
// Editor/\`tsc\` only — the moi bundler needs no declarations.

declare module 'moi' {
  // Absolute URL to a workspace file, streamed by the server. Pass a
  // workspace-relative path (e.g. 'clips/001.mp4'). Media/asset files only.
  export function fileUrl(path: string): string
  export type WidgetConfig = {
    rowSpan: 1 | 2 | 3 | 4
    colSpan: 1 | 2 | 3 | 4
    requiredEnv?: string[]
  }
  export type ViewConfig = { title?: string; requiredEnv?: string[] }
}

// Bundled asset imports (\`import logo from './logo.png'\`) resolve to a URL string.
declare module '*.png' { const s: string; export default s }
declare module '*.jpg' { const s: string; export default s }
declare module '*.jpeg' { const s: string; export default s }
declare module '*.gif' { const s: string; export default s }
declare module '*.webp' { const s: string; export default s }
declare module '*.avif' { const s: string; export default s }
declare module '*.svg' { const s: string; export default s }
`

// Bootstraps `.moi/` ONLY when it doesn't exist yet. Re-running `moi init`
// on an existing workspace overwrites skills but must leave the user's
// `.moi/` (their deps, widgets, lockfile) completely untouched.
// Returns 'exists' when skipped, otherwise the `bun install` exit code.
export async function scaffoldMoiDir(workspacePath: string): Promise<'exists' | number> {
  const moiDir = join(workspacePath, '.moi')
  if (await Bun.file(join(moiDir, 'package.json')).exists()) return 'exists'
  // A bare `.moi/` dir without package.json counts as not-bootstrapped —
  // fill in the missing pieces.

  await mkdir(join(moiDir, 'widgets'), { recursive: true })
  await Bun.write(join(moiDir, 'package.json'), JSON.stringify(MOI_PACKAGE_JSON, null, 2) + '\n')
  await Bun.write(join(moiDir, 'applet-env.d.ts'), APPLET_ENV_DTS)

  const install = Bun.spawn(['bun', 'install'], {
    cwd: moiDir,
    stdout: 'ignore',
    stderr: 'inherit'
  })
  return await install.exited
}
