// Scaffolding for a workspace's `.moi/` root, laid down by `moi init` (and
// `moi openclaw init`). Creates `.moi/widgets/`, writes the widget
// dependency manifest, and installs dependencies — so the agent never has to
// bootstrap the folder itself.
import { mkdir, rm } from 'node:fs/promises'
import { join, resolve, sep } from 'node:path'
import { isDeepStrictEqual } from 'node:util'

// Dependency set available to widgets. `react`/`react-dom` are stubs — at
// runtime they resolve to Moi's locally-vendored ESM via the browser importmap
// (/vendor/react); they're listed so editors pick up the correct types.
export const MOI_PACKAGE_JSON = {
  name: 'widgets',
  private: true,
  dependencies: {
    '@tabler/icons-react': '^3.40.0',
    tailwindcss: '^4.0.0',
    react: '^19.0.0',
    'react-dom': '^19.0.0'
  },
  devDependencies: {
    '@types/react': '^19.0.0',
    '@types/react-dom': '^19.0.0'
  }
} as const

// Dependency installation is helpful for editor types and widget builds, but
// it must never block workspace creation indefinitely when the registry is
// unreachable. A non-zero exit remains non-fatal to callers.
const INSTALL_TIMEOUT_MS = 15_000
const INSTALL_PENDING_FILE = '.install-pending'

type InstallDependencies = (moiDir: string) => Promise<number>

async function runBunInstall(moiDir: string): Promise<number> {
  const install = Bun.spawn(['bun', 'install'], {
    cwd: moiDir,
    stdout: 'ignore',
    stderr: 'inherit',
    timeout: INSTALL_TIMEOUT_MS,
    killSignal: 'SIGKILL'
  })
  return install.exited
}

async function isGeneratedManifest(packagePath: string): Promise<boolean> {
  try {
    const parsed = await Bun.file(packagePath).json()
    return isDeepStrictEqual(parsed, MOI_PACKAGE_JSON)
  } catch {
    return false
  }
}

// Ambient types for applets (widgets & views). Editor DX only — the moi
// bundler resolves the `moi` module and asset imports at build time without any
// declarations. Lives at `.moi/` root, NOT inside widgets/views, so it isn't
// picked up by the `.ts` build glob and compiled as an applet.
export const APPLET_ENV_DTS = `// Auto-generated by \`moi init\`. Ambient types for widgets & views.
// Editor/\`tsc\` only — the moi bundler needs no declarations.

declare module 'moi' {
  // Absolute URL to a workspace file, streamed by the server. Pass a
  // workspace-relative path (e.g. 'clips/001.mp4'). Media/asset files only.
  export function fileUrl(path: string): string
  export type WidgetConfig = {
    rowSpan: 1 | 2 | 3 | 4
    colSpan: 1 | 2 | 3 | 4
    requiredEnv?: string[]
  }
  export type ViewConfig = { title?: string; requiredEnv?: string[] }
}

// Bundled asset imports (\`import logo from './logo.png'\`) resolve to a URL string.
declare module '*.png' { const s: string; export default s }
declare module '*.jpg' { const s: string; export default s }
declare module '*.jpeg' { const s: string; export default s }
declare module '*.gif' { const s: string; export default s }
declare module '*.webp' { const s: string; export default s }
declare module '*.avif' { const s: string; export default s }
declare module '*.svg' { const s: string; export default s }
`

// Bootstraps `.moi/` ONLY when it doesn't exist yet. Re-running `moi init`
// on an existing workspace overwrites skills but must leave the user's
// `.moi/` (their deps, widgets, lockfile) completely untouched.
// Returns 'exists' when skipped, otherwise the `bun install` exit code.
export async function scaffoldMoiDir(
  workspacePath: string,
  installDependencies: InstallDependencies = runBunInstall
): Promise<'exists' | number> {
  // Backstop against the nested-workspace bug: never scaffold a `.moi/` *inside*
  // another workspace's `.moi/` (which produces the junk `.moi/.moi`). Callers
  // (`moi init`) lift to the workspace root via `liftToWorkspaceRoot` first, so
  // this only fires on a programmer error.
  if (resolve(workspacePath).split(sep).includes('.moi')) {
    throw new Error(
      `Refusing to scaffold a workspace inside a .moi directory: ${workspacePath}. ` +
        'Run from the workspace root.'
    )
  }
  const moiDir = join(workspacePath, '.moi')
  const packagePath = join(moiDir, 'package.json')
  const pendingPath = join(moiDir, INSTALL_PENDING_FILE)
  const packageExists = await Bun.file(packagePath).exists()
  const pendingInstall = await Bun.file(pendingPath).exists()
  // Recover workspaces left by an interrupted pre-marker install. Only retry a
  // manifest structurally equal to Moi's generated package, so a user-owned
  // `.moi/package.json` remains untouched.
  const generatedButIncomplete =
    packageExists &&
    !pendingInstall &&
    (await isGeneratedManifest(packagePath)) &&
    !(await Bun.file(join(moiDir, 'bun.lock')).exists()) &&
    !(await Bun.file(join(moiDir, 'bun.lockb')).exists()) &&
    !(await Bun.file(join(moiDir, 'node_modules')).exists())
  if (packageExists && !pendingInstall && !generatedButIncomplete) return 'exists'
  // A bare `.moi/` dir without package.json counts as not-bootstrapped —
  // fill in the missing pieces.

  if (!packageExists) {
    await mkdir(join(moiDir, 'widgets'), { recursive: true })
    await Bun.write(packagePath, JSON.stringify(MOI_PACKAGE_JSON, null, 2) + '\n')
    await Bun.write(join(moiDir, 'applet-env.d.ts'), APPLET_ENV_DTS)
  }

  // The marker survives timeouts, process crashes, and failed installs. A later
  // `moi init` then retries instead of treating the generated manifest as a
  // completed scaffold.
  await Bun.write(pendingPath, '')
  const exitCode = await installDependencies(moiDir)
  if (exitCode === 0) await rm(pendingPath, { force: true })
  return exitCode
}
