// Serves the locally-vendored React ESM (client/vendor/react, generated by
// scripts/build-vendor.ts) behind the stable `/vendor/react/*` URLs the
// importmap in client/index.html points at. This is what makes Moi run offline
// — no esm.sh fetch.
//
// The importmap URLs carry no dev/prod distinction; we pick the build here so
// developers get React's warnings (invalid hook calls, key warnings) while
// production gets the smaller build. `client/` ships in the published package
// (see package.json `files`), so this resolves in a global install too.
import { join } from 'node:path'

import { prebuilt } from './static'

const VENDOR_DIR = join(import.meta.dir, '..', 'client', 'vendor', 'react')
const MODE = prebuilt ? 'production' : 'development'

// A single flat file (`react.js`) or one nested under `_impl/` — both `.js`,
// no traversal. Matches exactly the layout build-vendor.ts emits.
const ALLOWED = /^(_impl\/)?[a-zA-Z0-9_-]+\.js$/

export async function serveVendorReact(req: Request): Promise<Response> {
  const rel = new URL(req.url).pathname.replace(/^\/vendor\/react\//, '')
  if (!ALLOWED.test(rel) || rel.includes('..')) {
    return new Response('Not found', { status: 404 })
  }
  const file = Bun.file(join(VENDOR_DIR, MODE, rel))
  if (!(await file.exists())) {
    return new Response('Not found', { status: 404 })
  }
  return new Response(file, {
    headers: {
      'Content-Type': 'text/javascript; charset=utf-8',
      // Stable URL across versions, so don't cache immutably — revalidate so a
      // `vendor:react` regen after a React bump is picked up.
      'Cache-Control': prebuilt ? 'public, max-age=3600' : 'no-store'
    }
  })
}
