// Frontier model catalog: the families a curated model picker features up
// front. Backends that merge huge catalogs (Hermes lists ~60 models across its
// configured providers) show only these and tuck the rest behind "More
// models". Lives in lib/ so the same curation is shared by any harness,
// client- or server-side.
//
// Two data sources with different jobs:
// - FRONTIER_FAMILIES below is hand-curated. No dataset ranks families by
//   prominence or tier (models.dev's `family` field mixes granularities —
//   `kimi-free`, `qwen3.7-max`), so which families matter, in what order, and
//   what counts as a demoted tier stays a table here. Expect to refresh it a
//   few times a year as families ship.
// - Within a family, variants (Opus 4 vs 4.8 vs 5) are ranked by release date
//   from `./frontier-catalog`, a committed snapshot of models.dev generated by
//   `scripts/update-frontier-catalog.ts` — data at runtime, moi stays offline.

import { FRONTIER_RELEASE_DATES } from './frontier-catalog'
import type { Model } from './types'

type FrontierFamily = {
  id: string
  // Tested against the lowercased `value` + `displayName` + `resolvedModel`.
  pattern: RegExp
}

// Order is rank: earlier families claim featured slots first. Model tiers that
// deserve their own slot (Opus vs Sonnet vs Haiku) are separate families —
// release-date ranking alone would let a newer small tier shadow the flagship.
// First match wins, so the bare `claude` catch-all stays last.
export const FRONTIER_FAMILIES: readonly FrontierFamily[] = [
  { id: 'claude-fable', pattern: /fable/ },
  { id: 'claude-opus', pattern: /opus/ },
  { id: 'gpt', pattern: /gpt-?[5-9]/ },
  { id: 'gemini', pattern: /gemini/ },
  { id: 'claude-sonnet', pattern: /sonnet/ },
  { id: 'grok', pattern: /grok/ },
  { id: 'deepseek', pattern: /deepseek/ },
  { id: 'kimi', pattern: /kimi/ },
  { id: 'qwen', pattern: /qwen/ },
  { id: 'glm', pattern: /glm/ },
  { id: 'claude-haiku', pattern: /haiku/ },
  { id: 'gpt-oss', pattern: /gpt-oss/ },
  { id: 'llama', pattern: /llama/ },
  { id: 'mistral', pattern: /mistral/ },
  { id: 'claude', pattern: /claude/ }
]

// Variant suffixes that never represent their family: small tiers (a `-flash`
// refresh is often newer than the flagship it trails) and non-chat modality
// models (`grok-imagine-image-2.0`). These rank below every full-strength
// variant regardless of release date and never claim a family's featured slot
// while other families still have full-strength candidates. Ollama's `:latest`
// tag is deliberately absent — there it marks the default pull, not a tier.
const DEMOTED_TIER =
  /(^|-)(mini|nano|lite|flash|fast|air|free|exp|preview|tiny|small|safeguard|imagine|image|video|audio)(-|$)/

export const FEATURED_MODELS_CAP = 5

// Snapshot keys and lookups share one spelling: lowercase, vendor prefix
// dropped, separator runs collapsed to `-` (`anthropic/claude-opus-4.8` and
// `claude-opus-4-8` both → `claude-opus-4-8`, `gpt-oss:20b` → `gpt-oss-20b`).
export function normalizeModelKey(id: string): string {
  return id
    .slice(id.lastIndexOf('/') + 1)
    .toLowerCase()
    .replace(/[._:\s]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
}

function frontierRank(key: string): number | undefined {
  const rank = FRONTIER_FAMILIES.findIndex(family => family.pattern.test(key))
  return rank === -1 ? undefined : rank
}

function modelKey(model: Model): string {
  return `${model.value} ${model.displayName} ${model.resolvedModel ?? ''}`.toLowerCase()
}

// An id the snapshot has never seen sorts as newest: within a frontier family
// it is far more often a model released after the snapshot than something
// worth hiding, and a stale snapshot must not bury a brand-new flagship.
const UNKNOWN_RELEASE = '9999-99-99'

function normalizedIds(model: Model): string[] {
  const ids = [model.displayName, model.value, model.resolvedModel]
  return ids.filter((id): id is string => !!id).map(normalizeModelKey)
}

function releaseDateOf(ids: readonly string[], releaseDates: Record<string, string>): string {
  for (const id of ids) {
    const date = releaseDates[id]
    if (date) return date
  }
  return UNKNOWN_RELEASE
}

type RankedModel = { model: Model; index: number; rank: number; demoted: boolean; date: string }

// The curated slice of one provider's list: up to `cap` frontier models,
// ordered by family rank. Every family's newest full-strength variant gets a
// slot before any family gets a second, so a provider with many Claude
// variants still surfaces Gemini and DeepSeek; demoted tiers only fill
// whatever slots remain. Returns [] when nothing matches — the caller decides
// the fallback.
export function featuredModels(
  models: readonly Model[],
  cap = FEATURED_MODELS_CAP,
  releaseDates: Record<string, string> = FRONTIER_RELEASE_DATES
): Model[] {
  const matched: RankedModel[] = []
  for (const [index, model] of models.entries()) {
    const rank = frontierRank(modelKey(model))
    if (rank === undefined) continue
    const ids = normalizedIds(model)
    matched.push({
      model,
      index,
      rank,
      demoted: ids.some(id => DEMOTED_TIER.test(id)),
      date: releaseDateOf(ids, releaseDates)
    })
  }
  matched.sort(
    (a, b) =>
      a.rank - b.rank ||
      Number(a.demoted) - Number(b.demoted) ||
      b.date.localeCompare(a.date) ||
      a.index - b.index
  )

  const picked = new Set<RankedModel>()
  const families = new Set<number>()
  for (const entry of matched) {
    if (picked.size >= cap) break
    if (entry.demoted || families.has(entry.rank)) continue
    families.add(entry.rank)
    picked.add(entry)
  }
  for (const entry of matched) {
    if (picked.size >= cap) break
    picked.add(entry)
  }

  return [...matched.filter(entry => picked.has(entry))].map(entry => entry.model)
}
