import { describe, expect, test } from 'bun:test'

import { classifySystemMessage, filterSystemText } from './system-messages'

// Real payloads as Claude Code writes them (verified against CLI transcripts).
const COMMAND_RECORD =
  '<command-name>/clear</command-name>\n' +
  '<command-message>clear</command-message>\n' +
  '<command-args></command-args>'

const REMINDER = '<system-reminder>\nAs you answer, remember X.\n</system-reminder>'

function matchedIds(text: string): string[] {
  return filterSystemText(text).matched.map(r => r.id)
}

describe('filterSystemText — hide rules', () => {
  test('slash-command record is fully consumed', () => {
    const f = filterSystemText(COMMAND_RECORD)
    expect(f.text).toBe('')
    expect(matchedIds(COMMAND_RECORD)).toEqual(['claude-code:slash-command'])
  })

  test('command record with message tag first is consumed', () => {
    const f = filterSystemText(
      '<command-message>review is running…</command-message>\n<command-name>/review</command-name>'
    )
    expect(f.text).toBe('')
  })

  test('local command stdout/stderr are consumed', () => {
    expect(filterSystemText('<local-command-stdout>Compacted.</local-command-stdout>').text).toBe(
      ''
    )
    expect(filterSystemText('<local-command-stderr>boom</local-command-stderr>').text).toBe('')
  })

  test('interrupt markers are consumed, both variants, with whitespace', () => {
    expect(filterSystemText('[Request interrupted by user]').text).toBe('')
    expect(filterSystemText('[Request interrupted by user for tool use]').text).toBe('')
    expect(filterSystemText('  [Request interrupted by user]\n').text).toBe('')
    expect(matchedIds('[Request interrupted by user]')).toEqual(['claude-code:interrupt'])
  })

  test('interrupt marker inside a longer message is kept', () => {
    const text = '[Request interrupted by user] — why did that happen?'
    expect(filterSystemText(text).text).toBe(text)
  })

  test('bash-mode input and output are consumed', () => {
    expect(filterSystemText('<bash-input>ls -la</bash-input>').text).toBe('')
    expect(
      filterSystemText('<bash-stdout>README.md</bash-stdout><bash-stderr></bash-stderr>').text
    ).toBe('')
  })

  test('memory input is consumed', () => {
    expect(filterSystemText('<user-memory-input>always use bun</user-memory-input>').text).toBe('')
  })

  test('task notifications are consumed, local and cloud shapes', () => {
    expect(filterSystemText('<task-notification>\n<task-id>b1</task-id>').text).toBe('')
    expect(
      filterSystemText('[SYSTEM NOTIFICATION - NOT USER INPUT]\nThis is an automated event.').text
    ).toBe('')
  })

  test('local-command caveat is consumed', () => {
    expect(
      filterSystemText(
        'Caveat: The messages below were generated by the user while running local commands. DO NOT respond to these messages.'
      ).text
    ).toBe('')
  })

  test('compact continuation summary is consumed', () => {
    expect(
      filterSystemText(
        'This session is being continued from a previous conversation that ran out of context. The summary below covers the earlier portion of the conversation.'
      ).text
    ).toBe('')
  })
})

describe('filterSystemText — strip rules', () => {
  test('system-reminder spans strip, surrounding text survives', () => {
    const f = filterSystemText(`${REMINDER}\nfix the login bug`)
    expect(f.text).toBe('fix the login bug')
    expect(f.matched.map(r => r.id)).toEqual(['claude-code:system-reminder'])
  })

  test('reminder-only block strips to empty', () => {
    const f = filterSystemText(REMINDER)
    expect(f.text).toBe('')
    expect(f.matched.length).toBe(1)
  })

  test('multiple reminder spans all strip', () => {
    const f = filterSystemText(`${REMINDER}\nreal text\n${REMINDER}`)
    expect(f.text).toBe('real text')
  })

  test('prompt-submit hook output strips', () => {
    const f = filterSystemText(
      'deploy it\n<user-prompt-submit-hook>lint ok</user-prompt-submit-hook>'
    )
    expect(f.text).toBe('deploy it')
    expect(f.matched.map(r => r.id)).toEqual(['claude-code:prompt-submit-hook'])
  })
})

describe('filterSystemText — real text passes through', () => {
  test('plain text is untouched, spacing preserved', () => {
    const text = '  keep my   spacing\n\nand lines '
    const f = filterSystemText(text)
    expect(f.text).toBe(text)
    expect(f.matched).toEqual([])
  })

  test('mentioning an envelope mid-message is not a match', () => {
    const text = 'why does the transcript contain <command-name> tags?'
    expect(filterSystemText(text).text).toBe(text)
  })
})

describe('classifySystemMessage', () => {
  test('single command record classifies as slash-command', () => {
    expect(classifySystemMessage([COMMAND_RECORD])?.reason).toBe('slash-command')
  })

  test('interrupt marker classifies as interrupt', () => {
    expect(classifySystemMessage(['[Request interrupted by user]'])?.reason).toBe('interrupt')
  })

  test('all-machinery multi-block message classifies by first rule', () => {
    const verdict = classifySystemMessage([COMMAND_RECORD, REMINDER])
    expect(verdict?.reason).toBe('slash-command')
    expect(verdict?.rules.map(r => r.id)).toEqual([
      'claude-code:slash-command',
      'claude-code:system-reminder'
    ])
  })

  test('machinery plus real text does not classify', () => {
    expect(classifySystemMessage([COMMAND_RECORD, 'and also fix the tests'])).toBeUndefined()
    expect(classifySystemMessage([`${REMINDER}\nreal ask`])).toBeUndefined()
  })

  test('blank blocks neither veto nor count', () => {
    expect(classifySystemMessage(['  \n', COMMAND_RECORD])?.reason).toBe('slash-command')
    expect(classifySystemMessage(['   '])).toBeUndefined()
    expect(classifySystemMessage([])).toBeUndefined()
  })

  test('plain user text does not classify', () => {
    expect(classifySystemMessage(['рун'])).toBeUndefined()
  })
})
