export { CollabProvider, AppletPresenceProvider, useCollabEnabled } from './provider'
export { WorkspaceCollabControls } from './components/workspace-collab-controls'
export type { TabInfo } from './components/workspace-collab-controls'
export { appletCollabApi } from './applet-api'
export type { AppletCollabApi } from './applet-api'
