import type { Icon } from '@tabler/icons-react'
import {
  IconActivity,
  IconApi,
  IconAtom,
  IconBell,
  IconBolt,
  IconBook,
  IconBrain,
  IconBriefcase,
  IconBug,
  IconBulb,
  IconCalendar,
  IconCamera,
  IconChartBar,
  IconChefHat,
  IconCloud,
  IconCode,
  IconCompass,
  IconCpu,
  IconCube,
  IconDatabase,
  IconDeviceGamepad2,
  IconDiamond,
  IconFeather,
  IconFile,
  IconFlame,
  IconFlask,
  IconFolder,
  IconGhost,
  IconGift,
  IconGlobe,
  IconHeart,
  IconHexagon,
  IconHome,
  IconKey,
  IconLeaf,
  IconMail,
  IconMap,
  IconMessage,
  IconMoon,
  IconMountain,
  IconMusic,
  IconPalette,
  IconPaperclip,
  IconPhoto,
  IconPlanet,
  IconPlug,
  IconRobot,
  IconRocket,
  IconSettings,
  IconShield,
  IconShoppingCart,
  IconSnowflake,
  IconSparkles,
  IconStar,
  IconSun,
  IconTarget,
  IconTerminal2,
  IconTool,
  IconTrophy,
  IconUser,
  IconWand,
  IconWorld
} from '@tabler/icons-react'

export const ICON_CHOICES: { id: string; Icon: Icon }[] = [
  { id: 'rocket', Icon: IconRocket },
  { id: 'sparkles', Icon: IconSparkles },
  { id: 'bolt', Icon: IconBolt },
  { id: 'flame', Icon: IconFlame },
  { id: 'star', Icon: IconStar },
  { id: 'heart', Icon: IconHeart },
  { id: 'diamond', Icon: IconDiamond },
  { id: 'trophy', Icon: IconTrophy },
  { id: 'target', Icon: IconTarget },
  { id: 'bulb', Icon: IconBulb },
  { id: 'brain', Icon: IconBrain },
  { id: 'robot', Icon: IconRobot },
  { id: 'wand', Icon: IconWand },
  { id: 'atom', Icon: IconAtom },
  { id: 'flask', Icon: IconFlask },
  { id: 'cpu', Icon: IconCpu },
  { id: 'code', Icon: IconCode },
  { id: 'terminal', Icon: IconTerminal2 },
  { id: 'api', Icon: IconApi },
  { id: 'database', Icon: IconDatabase },
  { id: 'cube', Icon: IconCube },
  { id: 'hexagon', Icon: IconHexagon },
  { id: 'plug', Icon: IconPlug },
  { id: 'tool', Icon: IconTool },
  { id: 'settings', Icon: IconSettings },
  { id: 'bug', Icon: IconBug },
  { id: 'activity', Icon: IconActivity },
  { id: 'chart', Icon: IconChartBar },
  { id: 'briefcase', Icon: IconBriefcase },
  { id: 'folder', Icon: IconFolder },
  { id: 'file', Icon: IconFile },
  { id: 'book', Icon: IconBook },
  { id: 'message', Icon: IconMessage },
  { id: 'mail', Icon: IconMail },
  { id: 'bell', Icon: IconBell },
  { id: 'paperclip', Icon: IconPaperclip },
  { id: 'key', Icon: IconKey },
  { id: 'shield', Icon: IconShield },
  { id: 'user', Icon: IconUser },
  { id: 'home', Icon: IconHome },
  { id: 'globe', Icon: IconGlobe },
  { id: 'world', Icon: IconWorld },
  { id: 'planet', Icon: IconPlanet },
  { id: 'compass', Icon: IconCompass },
  { id: 'map', Icon: IconMap },
  { id: 'calendar', Icon: IconCalendar },
  { id: 'cloud', Icon: IconCloud },
  { id: 'sun', Icon: IconSun },
  { id: 'moon', Icon: IconMoon },
  { id: 'snowflake', Icon: IconSnowflake },
  { id: 'leaf', Icon: IconLeaf },
  { id: 'mountain', Icon: IconMountain },
  { id: 'feather', Icon: IconFeather },
  { id: 'ghost', Icon: IconGhost },
  { id: 'music', Icon: IconMusic },
  { id: 'camera', Icon: IconCamera },
  { id: 'photo', Icon: IconPhoto },
  { id: 'palette', Icon: IconPalette },
  { id: 'gamepad', Icon: IconDeviceGamepad2 },
  { id: 'gift', Icon: IconGift },
  { id: 'cart', Icon: IconShoppingCart },
  { id: 'chef', Icon: IconChefHat }
]

export const FAVORITE_EMOJI = [
  '🚀',
  '✨',
  '🔥',
  '⚡',
  '💡',
  '🧠',
  '🤖',
  '🪄',
  '🧪',
  '⚙️',
  '🛠️',
  '💻',
  '📦',
  '📊',
  '📈',
  '📝',
  '📚',
  '🎯',
  '🏆',
  '💎',
  '🪐',
  '🌍',
  '🧭',
  '🎨',
  '🎮',
  '☕'
]

export const EMOJI_FONT = 'font-[Apple_Color_Emoji,Segoe_UI_Emoji,Noto_Color_Emoji,sans-serif]'
