// Regenerates lib/frontier-catalog.ts from models.dev — the release-date
// snapshot behind lib/frontier-models.ts variant ranking. Run whenever the
// frontier picker starts missing a newly shipped model:
//
//   bun scripts/update-frontier-catalog.ts [path-to-api.json]
//
// models.dev (https://github.com/sst/models.dev, MIT) aggregates every
// provider's catalog. Only models matching a FRONTIER_FAMILIES pattern are
// kept, keyed by normalized id. The same id appears under many providers with
// disagreeing dates — some report their own listing date or plain junk
// (1970-01-01) — so each key gets the most common date across providers,
// earliest on a tie.

import { FRONTIER_FAMILIES, normalizeModelKey } from '../lib/frontier-models'

const SOURCE_URL = 'https://models.dev/api.json'
const OUT_PATH = new URL('../lib/frontier-catalog.ts', import.meta.url).pathname

type CatalogModel = { release_date?: string }
type CatalogProvider = { models: Record<string, CatalogModel> }

const localPath = process.argv[2]
const data: Record<string, CatalogProvider> = localPath
  ? await Bun.file(localPath).json()
  : await (await fetch(SOURCE_URL)).json()

const votes = new Map<string, Map<string, number>>()
for (const provider of Object.values(data)) {
  for (const [id, model] of Object.entries(provider.models)) {
    const key = normalizeModelKey(id)
    if (!key || !FRONTIER_FAMILIES.some(family => family.pattern.test(key))) continue
    const date = model.release_date
    if (!date || !/^\d{4}-\d{2}-\d{2}$/.test(date) || date < '2015-01-01') continue
    const counts = votes.get(key) ?? new Map<string, number>()
    counts.set(date, (counts.get(date) ?? 0) + 1)
    votes.set(key, counts)
  }
}

const dates = new Map<string, string>()
for (const [key, counts] of votes) {
  const best = [...counts.entries()].sort(
    ([dateA, countA], [dateB, countB]) => countB - countA || dateA.localeCompare(dateB)
  )[0]
  if (best) dates.set(key, best[0])
}

const entries = [...dates.entries()].sort(([a], [b]) => a.localeCompare(b))
const body = entries.map(([key, date]) => `  '${key}': '${date}'`).join(',\n')

const header = `// Generated by scripts/update-frontier-catalog.ts — do not edit by hand.
// Release dates (YYYY-MM-DD) for frontier-family models, snapshotted from
// models.dev so ranking works offline. Refresh with:
//
//   bun scripts/update-frontier-catalog.ts

export const FRONTIER_RELEASE_DATES: Record<string, string> = {
`

await Bun.write(OUT_PATH, `${header}${body}\n}\n`)
console.log(`Wrote ${entries.length} models to lib/frontier-catalog.ts`)
